// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_middleware.ts";
import * as $1 from "./routes/api/login.ts";
import * as $2 from "./routes/api/logout.ts";
import * as $3 from "./routes/api/movement.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/login.tsx";
import * as $6 from "./routes/movement/[id].tsx";
import * as $7 from "./routes/movement/index.tsx";
import * as $$0 from "./islands/CtgrSelectOptions.tsx";
import * as $$1 from "./islands/Deleter.tsx";
import * as $$2 from "./islands/MainTable.tsx";
import * as $$3 from "./islands/SideMenu.tsx";
import * as $$4 from "./islands/ToastsWrap.tsx";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $0,
    "./routes/api/login.ts": $1,
    "./routes/api/logout.ts": $2,
    "./routes/api/movement.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/login.tsx": $5,
    "./routes/movement/[id].tsx": $6,
    "./routes/movement/index.tsx": $7,
  },
  islands: {
    "./islands/CtgrSelectOptions.tsx": $$0,
    "./islands/Deleter.tsx": $$1,
    "./islands/MainTable.tsx": $$2,
    "./islands/SideMenu.tsx": $$3,
    "./islands/ToastsWrap.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
